// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240306110831_NewData")]
    partial class NewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAcquisition = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAcquisition = new DateTime(2001, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 9, 9, 23, 0, 0, 0, DateTimeKind.Utc),
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 1,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8625),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8667),
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 2,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8685),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8692),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 3,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8704),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8710),
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 4,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8720),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8725),
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 5,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8735),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8741),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 6,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8750),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8757),
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 7,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8922),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8933),
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 8,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8946),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8953),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 9,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8965),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8972),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 10,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8983),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(8990),
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 11,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9001),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9008),
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 12,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9018),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9025),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 13,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9037),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9044),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 14,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9055),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9062),
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 15,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9073),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9080),
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 16,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9092),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9099),
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 17,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9108),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9114),
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 18,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9126),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9134),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 19,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9146),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9152),
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 20,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9163),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9170),
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 21,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9179),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9184),
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 22,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9194),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9200),
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 23,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9209),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9216),
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 24,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9227),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9234),
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 25,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9245),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9251),
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 26,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9263),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9269),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 27,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9279),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9285),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 28,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9296),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9302),
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 29,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9313),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9318),
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 30,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9327),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9335),
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 31,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9346),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9353),
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 32,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9363),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9371),
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 33,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9384),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9392),
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 34,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9404),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9412),
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 35,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9425),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9431),
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 36,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9442),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9449),
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 37,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9459),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9464),
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 38,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9474),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9481),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 39,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9490),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9496),
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 40,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9506),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9511),
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 41,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9521),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9528),
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 42,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9537),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9543),
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 43,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9552),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9558),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 44,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9567),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9574),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 45,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9584),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9591),
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 46,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9603),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9609),
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 47,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9621),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9629),
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 48,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9641),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9649),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 49,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9663),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9669),
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 50,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9679),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9686),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 51,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9697),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9703),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 52,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9715),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9721),
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 53,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9731),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9736),
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 54,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9746),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9753),
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 55,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9763),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9768),
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 56,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9778),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9783),
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 57,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9793),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9799),
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 58,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9808),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9813),
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 59,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9823),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9829),
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 60,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9837),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9843),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 61,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9855),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9863),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 62,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9873),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9878),
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 63,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9889),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9897),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 64,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9908),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9914),
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 65,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9927),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9935),
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 66,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9945),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9952),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 67,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9962),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9967),
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 68,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9976),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9983),
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 69,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9993),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 111, DateTimeKind.Utc).AddTicks(9999),
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 70,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(9),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(16),
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 71,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(25),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(32),
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 72,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(44),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(52),
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 73,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(64),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(69),
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 74,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(81),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(87),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 75,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(98),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(104),
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 76,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(113),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(119),
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 77,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(127),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(133),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 78,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(143),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(149),
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 79,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(159),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(167),
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 80,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(191),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(198),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 81,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(214),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(220),
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            Id = 82,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(229),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(235),
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 83,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(246),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(252),
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 84,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(263),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(270),
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 85,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(279),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(286),
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 86,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(297),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(303),
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 87,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(313),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(319),
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 88,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(330),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(336),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = 89,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(346),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(353),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 90,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(366),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(374),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            Id = 91,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(387),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(395),
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 92,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(407),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(414),
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 93,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(537),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(547),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 94,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(559),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(566),
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            Id = 95,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(576),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(583),
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 96,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(593),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(600),
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            Id = 97,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(610),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(616),
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 98,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(625),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(632),
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 99,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(641),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(648),
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            Id = 100,
                            DateOfAcquisition = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(661),
                            DateOfBirth = new DateTime(2024, 3, 6, 11, 8, 31, 112, DateTimeKind.Utc).AddTicks(668),
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 4
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = 1,
                            Classification = 0,
                            Name = "elephant"
                        },
                        new
                        {
                            Id = 2,
                            Classification = 0,
                            Name = "zebra"
                        },
                        new
                        {
                            Id = 3,
                            Classification = 1,
                            Name = "snake"
                        },
                        new
                        {
                            Id = 4,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            Id = 5,
                            Classification = 3,
                            Name = "spider"
                        },
                        new
                        {
                            Id = 6,
                            Classification = 0,
                            Name = "hippo"
                        },
                        new
                        {
                            Id = 7,
                            Classification = 2,
                            Name = "parrot"
                        },
                        new
                        {
                            Id = 8,
                            Classification = 4,
                            Name = "goldfish"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
