// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240307113745_AddEnclosure")]
    partial class AddEnclosure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnimalId"));

                    b.Property<DateTime>("DateOfAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("AnimalId");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4499),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4565),
                            EnclosureId = 1,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 2,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4663),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4666),
                            EnclosureId = 5,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 3,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4671),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4673),
                            EnclosureId = 2,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 4,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4677),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4679),
                            EnclosureId = 5,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 5,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4683),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4685),
                            EnclosureId = 5,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 6,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4689),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4692),
                            EnclosureId = 3,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 7,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4696),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4698),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 8,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4702),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4705),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 9,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4708),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4711),
                            EnclosureId = 1,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 10,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4715),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4717),
                            EnclosureId = 4,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 11,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4721),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4723),
                            EnclosureId = 1,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 12,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4727),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4729),
                            EnclosureId = 4,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 13,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4733),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4736),
                            EnclosureId = 4,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 14,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4740),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4742),
                            EnclosureId = 1,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 15,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4746),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4748),
                            EnclosureId = 1,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 16,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4752),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4755),
                            EnclosureId = 3,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 17,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4758),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4761),
                            EnclosureId = 1,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 18,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4765),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4767),
                            EnclosureId = 5,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 19,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4771),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4773),
                            EnclosureId = 3,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 20,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4777),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4780),
                            EnclosureId = 3,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 21,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4784),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4786),
                            EnclosureId = 5,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 22,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4790),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4792),
                            EnclosureId = 2,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 23,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4796),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4798),
                            EnclosureId = 2,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 24,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4802),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4805),
                            EnclosureId = 5,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 25,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4808),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4811),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 26,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4814),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4817),
                            EnclosureId = 2,
                            Name = "Tabatha",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 27,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4821),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4823),
                            EnclosureId = 3,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 28,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4827),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4829),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 29,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4833),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4836),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 30,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4839),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4842),
                            EnclosureId = 4,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 31,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4846),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4848),
                            EnclosureId = 1,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 32,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4852),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4854),
                            EnclosureId = 4,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 33,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4858),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4861),
                            EnclosureId = 5,
                            Name = "Peter",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 34,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4864),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4867),
                            EnclosureId = 5,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 35,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4871),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4873),
                            EnclosureId = 2,
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 36,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4877),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4879),
                            EnclosureId = 3,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 37,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4883),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4886),
                            EnclosureId = 3,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 38,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4889),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4892),
                            EnclosureId = 5,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 39,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4896),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4898),
                            EnclosureId = 4,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 40,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4902),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4904),
                            EnclosureId = 2,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 41,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4908),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4910),
                            EnclosureId = 3,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 42,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4914),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4917),
                            EnclosureId = 5,
                            Name = "Mickey",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 43,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4921),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4923),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 44,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4927),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4929),
                            EnclosureId = 1,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 45,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4933),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4935),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 46,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4939),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4942),
                            EnclosureId = 2,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 47,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4946),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4948),
                            EnclosureId = 5,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 48,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4952),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4955),
                            EnclosureId = 1,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 49,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4958),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4961),
                            EnclosureId = 4,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 50,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4965),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4967),
                            EnclosureId = 4,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 51,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4971),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4973),
                            EnclosureId = 1,
                            Name = "Pooh",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 52,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4977),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4980),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 53,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4983),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4986),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 54,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4990),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4992),
                            EnclosureId = 5,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 55,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4996),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(4998),
                            EnclosureId = 3,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 56,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5002),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5004),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 57,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5008),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5011),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 58,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5014),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5017),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 59,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5021),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5023),
                            EnclosureId = 5,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 60,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5027),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5029),
                            EnclosureId = 4,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 61,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5033),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5035),
                            EnclosureId = 4,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 62,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5039),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5041),
                            EnclosureId = 3,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 63,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5045),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5048),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 64,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5051),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5054),
                            EnclosureId = 5,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 65,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5058),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5060),
                            EnclosureId = 2,
                            Name = "Spot",
                            Sex = 0,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 66,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5064),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5066),
                            EnclosureId = 2,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 67,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5070),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5072),
                            EnclosureId = 3,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 68,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5076),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5079),
                            EnclosureId = 4,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 69,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5082),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5085),
                            EnclosureId = 2,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 70,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5088),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5091),
                            EnclosureId = 4,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 71,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5095),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5097),
                            EnclosureId = 1,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 72,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5101),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5103),
                            EnclosureId = 2,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 73,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5107),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5110),
                            EnclosureId = 4,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 74,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5113),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5116),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 75,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5119),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5122),
                            EnclosureId = 1,
                            Name = "Spot",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 76,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5126),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5128),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 77,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5132),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5134),
                            EnclosureId = 5,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 78,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5138),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5140),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 79,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5144),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5147),
                            EnclosureId = 3,
                            Name = "Winston",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 80,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5150),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5153),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 81,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5197),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5200),
                            EnclosureId = 1,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 82,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5204),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5206),
                            EnclosureId = 1,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 83,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5210),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5213),
                            EnclosureId = 5,
                            Name = "Tabatha",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 84,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5217),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5219),
                            EnclosureId = 2,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 85,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5223),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5225),
                            EnclosureId = 5,
                            Name = "Mickey",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 86,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5229),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5231),
                            EnclosureId = 2,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 87,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5235),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5238),
                            EnclosureId = 5,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 3
                        },
                        new
                        {
                            AnimalId = 88,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5242),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5244),
                            EnclosureId = 4,
                            Name = "Pooh",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 89,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5248),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5250),
                            EnclosureId = 4,
                            Name = "Garfield",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 90,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5254),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5256),
                            EnclosureId = 5,
                            Name = "Daffy",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 91,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5260),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5263),
                            EnclosureId = 1,
                            Name = "Kanga",
                            Sex = 1,
                            SpeciesId = 7
                        },
                        new
                        {
                            AnimalId = 92,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5266),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5269),
                            EnclosureId = 2,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 93,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5273),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5275),
                            EnclosureId = 2,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 94,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5279),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5281),
                            EnclosureId = 2,
                            Name = "Daffy",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 95,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5285),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5288),
                            EnclosureId = 1,
                            Name = "Snoopy",
                            Sex = 1,
                            SpeciesId = 5
                        },
                        new
                        {
                            AnimalId = 96,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5291),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5294),
                            EnclosureId = 4,
                            Name = "Piglet",
                            Sex = 0,
                            SpeciesId = 1
                        },
                        new
                        {
                            AnimalId = 97,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5298),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5300),
                            EnclosureId = 3,
                            Name = "Piglet",
                            Sex = 1,
                            SpeciesId = 4
                        },
                        new
                        {
                            AnimalId = 98,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5304),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5306),
                            EnclosureId = 2,
                            Name = "Kanga",
                            Sex = 0,
                            SpeciesId = 6
                        },
                        new
                        {
                            AnimalId = 99,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5310),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5312),
                            EnclosureId = 1,
                            Name = "Snoopy",
                            Sex = 0,
                            SpeciesId = 2
                        },
                        new
                        {
                            AnimalId = 100,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5316),
                            DateOfBirth = new DateTime(2024, 3, 7, 11, 37, 45, 57, DateTimeKind.Utc).AddTicks(5319),
                            EnclosureId = 4,
                            Name = "Peter",
                            Sex = 1,
                            SpeciesId = 3
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Property<int>("EnclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnclosureId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfAnimals")
                        .HasColumnType("integer");

                    b.HasKey("EnclosureId");

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            EnclosureId = 1,
                            Name = "Lion’s Enclosure",
                            NumberOfAnimals = 10
                        },
                        new
                        {
                            EnclosureId = 2,
                            Name = "Aviary ",
                            NumberOfAnimals = 50
                        },
                        new
                        {
                            EnclosureId = 3,
                            Name = "Reptile House",
                            NumberOfAnimals = 40
                        },
                        new
                        {
                            EnclosureId = 4,
                            Name = "Giraffe Enclosure",
                            NumberOfAnimals = 6
                        },
                        new
                        {
                            EnclosureId = 5,
                            Name = "Hippo Enclosure",
                            NumberOfAnimals = 10
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpeciesId");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            Classification = 0,
                            Name = "elephant"
                        },
                        new
                        {
                            SpeciesId = 2,
                            Classification = 0,
                            Name = "zebra"
                        },
                        new
                        {
                            SpeciesId = 3,
                            Classification = 1,
                            Name = "snake"
                        },
                        new
                        {
                            SpeciesId = 4,
                            Classification = 0,
                            Name = "giraffe"
                        },
                        new
                        {
                            SpeciesId = 5,
                            Classification = 3,
                            Name = "spider"
                        },
                        new
                        {
                            SpeciesId = 6,
                            Classification = 0,
                            Name = "hippo"
                        },
                        new
                        {
                            SpeciesId = 7,
                            Classification = 2,
                            Name = "parrot"
                        },
                        new
                        {
                            SpeciesId = 8,
                            Classification = 4,
                            Name = "goldfish"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
